[package]
name = "tetris-rs"
version = "0.1.0"
edition = "2024"

[build-dependencies]

[dependencies]
crossterm = "0.27"
ratatui = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.10.0-rc.6"
anyhow = "1.0.100"
rodio = "0.21"
